server:
  port: 8080
  servlet:
    context-path: /komunalka

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: komunalka

api:
  version: /api/v1

http:
  currate:
    api-key: f496f28e86ec97168c39b9ce1920de38